import type { Metadata } from "next";

import Footer from "@/components/footer";

import { FONT_MONO, FONT_SANS, FONT_SERIF } from "@/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${FONT_SERIF.variable} ${FONT_SANS.variable} ${FONT_MONO.variable} bg-deep-black text-foreground-dark font-mono transition-colors`}
      >
        <div className="flex flex-col justify-between">
          <main>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
